name: 🐞 Bug
description: Report a bug or an issue you've found.
title: "[Bug] <title>"
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report.
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    attributes:
      label: Describe the issue
      description: A concise description of the problem you're experiencing. Also, please provide the steps to reproduce the issue if applicable.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant error log or model output
      description: |
        If applicable, provide the relevant error log or describe the problematic model output.
      render: shell
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected behavior
      description: A concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Context
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
